import { useMemo, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { searchFlights } from "../services/flightService";
import "./FlightSuggestions.css";
import { useCurrency } from "../context/CurrencyContext";
import { useAuth } from "../context/AuthContext";
import { recordSearch, saveProviderItem } from "../services/travelDataService";

const filterOptions = ["Non-stop", "1 Stop", "2+ Stops", "Morning Departure", "Afternoon Departure", "Evening Departure", "Night Departure", "Economy", "Premium Economy", "Business", "First Class"];
const cabinLabels = { ECONOMY: "Economy", PREMIUM_ECONOMY: "Premium Economy", BUSINESS: "Business", FIRST: "First Class" };
const airlineLogo = (code) => `https://images.kiwi.com/airlines/64/${encodeURIComponent(code || "XX")}.png`;
const time = (value) => value ? new Intl.DateTimeFormat(undefined, { hour: "numeric", minute: "2-digit" }).format(new Date(value)) : "—";
const duration = (value) => String(value || "").replace("PT", "").replace("H", "h ").replace("M", "m") || "—";
const departureHour = (flight) => new Date(flight.departure.time).getHours();

export default function FlightSuggestions({ destination }) {
  const { user } = useAuth();
  const [form, setForm] = useState({ departure: "", destination: destination || "", departureDate: "", returnDate: "", travelers: "1" });
  const [state, setState] = useState({ status: "idle", flights: [], error: "", source: "" });
  const [filters, setFilters] = useState([]); const [sort, setSort] = useState("Lowest Price"); const [airlineSearch, setAirlineSearch] = useState(""); const [selected, setSelected] = useState(null);
  const change = (event) => setForm((current) => ({ ...current, [event.target.name]: event.target.value }));
  const submit = async (event) => { event.preventDefault(); setState((current) => ({ ...current, status: "loading", error: "" })); try { const data = await searchFlights(form); setState({ status: "ready", flights: data.flights || [], error: "", source: data.source || "" }); if(user) void recordSearch(`${form.departure} to ${form.destination}`, "flight", { departureDate: form.departureDate, results: data.flights?.length || 0 }).catch(() => {}); } catch (error) { setState({ status: "error", flights: [], error: error.message, source: "" }); } };
  const flights = useMemo(() => state.flights.filter((flight) => {
    const hour = departureHour(flight); const cabin = cabinLabels[flight.cabin] || flight.cabin;
    const active = (filter) => !filters.includes(filter) || (filter === "Non-stop" && flight.stops === 0) || (filter === "1 Stop" && flight.stops === 1) || (filter === "2+ Stops" && flight.stops >= 2) || (filter === "Morning Departure" && hour >= 5 && hour < 12) || (filter === "Afternoon Departure" && hour >= 12 && hour < 17) || (filter === "Evening Departure" && hour >= 17 && hour < 21) || (filter === "Night Departure" && (hour >= 21 || hour < 5)) || filter === cabin;
    return filters.every(active) && `${flight.airline} ${flight.flightNumber}`.toLowerCase().includes(airlineSearch.toLowerCase());
  }).sort((a, b) => { if (sort === "Fastest Flight") return a.durationMinutes - b.durationMinutes; if (sort === "Earliest Departure") return new Date(a.departure.time) - new Date(b.departure.time); if (sort === "Latest Departure") return new Date(b.departure.time) - new Date(a.departure.time); if (sort === "Best Value") return (a.price / Math.max(a.durationMinutes, 1)) - (b.price / Math.max(b.durationMinutes, 1)); return a.price - b.price; }), [state.flights, filters, sort, airlineSearch]);
  const toggleFilter = (item) => setFilters((current) => current.includes(item) ? current.filter((value) => value !== item) : [...current, item]);
  return <section className="flight-suggestions"><div className="flight-heading"><div><p>TAKE THE SCENIC ROUTE</p><h2>Flight <em>Suggestions</em></h2><span>Compare flight options for your journey.</span></div></div><form className="flight-form" onSubmit={submit}><input name="departure" value={form.departure} onChange={change} placeholder="Departure city" required /><input name="destination" value={form.destination} onChange={change} placeholder="Destination city" required /><input name="departureDate" value={form.departureDate} onChange={change} type="date" required /><input name="returnDate" value={form.returnDate} onChange={change} type="date" min={form.departureDate || undefined} /><input name="travelers" value={form.travelers} onChange={change} type="number" min="1" max="9" aria-label="Travelers" required /><button type="submit">Search flights</button></form>
    {state.status === "loading" && <Skeleton />}{state.status === "error" && <Feedback error={state.error} />}{state.status === "ready" && <><div className="flight-controls"><input value={airlineSearch} onChange={(event) => setAirlineSearch(event.target.value)} placeholder="Filter airlines" aria-label="Filter airlines" /><label>Sort <select value={sort} onChange={(event) => setSort(event.target.value)}>{["Lowest Price", "Fastest Flight", "Earliest Departure", "Latest Departure", "Best Value"].map((item) => <option key={item}>{item}</option>)}</select></label></div><div className="flight-filters">{filterOptions.map((item) => <button type="button" key={item} className={filters.includes(item) ? "active" : ""} onClick={() => toggleFilter(item)}>{item}</button>)}</div>{state.source === "demo" && <p className="flight-note">Showing sample fares. Configure Amadeus on the server for live availability.</p>}{flights.length ? <motion.div layout className="flight-grid">{flights.map((flight, index) => <FlightCard flight={flight} index={index} onOpen={() => setSelected(flight)} key={flight.id} />)}</motion.div> : <Feedback />}</>}<AnimatePresence>{selected && <FlightModal flight={selected} onClose={() => setSelected(null)} />}</AnimatePresence></section>;
}
function FlightCard({ flight, index, onOpen }) { const { formatCurrency } = useCurrency(); return <motion.article layout className="flight-card" initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: Math.min(index * .04, .25) }} onClick={onOpen} role="button" tabIndex="0" onKeyDown={(event) => event.key === "Enter" && onOpen()}><div className="flight-airline"><img src={airlineLogo(flight.airlineCode)} alt="" onError={(event) => { event.currentTarget.style.display = "none"; }} /><span>{flight.airline}<small>{flight.flightNumber}</small></span>{/* Fare source currency is converted by the shared context. */}<b>{formatCurrency(flight.price, flight.currency, { maximumFractionDigits: 0 })}</b></div><div className="flight-route"><div><strong>{time(flight.departure.time)}</strong><span>{flight.departure.airport}</span></div><p><i />{duration(flight.duration)}<small>{flight.stops === 0 ? "Non-stop" : `${flight.stops} stop${flight.stops > 1 ? "s" : ""}`}</small></p><div><strong>{time(flight.arrival.time)}</strong><span>{flight.arrival.airport}</span></div></div><div className="flight-bottom"><span>{cabinLabels[flight.cabin] || flight.cabin}</span><span>{flight.baggage}</span><a href={flight.bookingUrl} target="_blank" rel="noreferrer" onClick={(event) => event.stopPropagation()}>Book Flight</a></div></motion.article>; }
function Skeleton() { return <div className="flight-grid">{Array.from({ length: 6 }, (_, index) => <div className="flight-skeleton" key={index}><i /><b /><b /></div>)}</div>; }
function Feedback({ error }) { return <div className={`flight-feedback ${error ? "error" : ""}`}><strong>{error ? "Flight search is unavailable" : "No flights match these preferences."}</strong><p>{error || "Try adjusting the filters or searching another route."}</p></div>; }
function FlightModal({ flight, onClose }) { const { formatCurrency } = useCurrency(); const { user } = useAuth(); const [saved,setSaved]=useState(false); const save=async()=>{if(!user){window.location.assign("/login");return;} await saveProviderItem("flights",flight);setSaved(true);}; return <motion.div className="flight-modal-backdrop" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onMouseDown={onClose}><motion.article className="flight-modal" initial={{ opacity: 0, y: 25 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: 25 }} onMouseDown={(event) => event.stopPropagation()}><button onClick={onClose} aria-label="Close flight details">×</button><p className="flight-kicker">{flight.airline} · {flight.flightNumber}</p><h2>{flight.departure.airport} to {flight.arrival.airport}</h2><p><b>{cabinLabels[flight.cabin] || flight.cabin}</b> · {flight.baggage}</p><div className="flight-itinerary">{flight.itinerary.map((segment, index) => <div key={`${segment.flightNumber}-${index}`}><strong>{segment.departure.airport} {time(segment.departure.time)} → {segment.arrival.airport} {time(segment.arrival.time)}</strong><span>{segment.airline} {segment.flightNumber} · {duration(segment.duration)} · Aircraft: {segment.aircraft || "Unavailable"} · Terminal: {segment.terminal || "Unavailable"}</span>{index < flight.itinerary.length - 1 && <em>Layover before next segment</em>}</div>)}</div><p><b>Fare rules:</b> {flight.fareRules || "Unavailable"}</p><div className="flight-modal-actions"><b>{formatCurrency(flight.price, flight.currency, { maximumFractionDigits: 0 })}</b><button type="button" onClick={save}>{saved?"✓ Saved":"♡ Save flight"}</button><a href={flight.bookingUrl} target="_blank" rel="noreferrer">Book Flight</a></div></motion.article></motion.div>; }
