import { fetchWithRetry } from "./providerRequest.mjs";

const fetch = fetchWithRetry;

// Provider boundary: replace this module or add another adapter without changing
// the Express route or React client contract.
const carrierNames = { AI: "Air India", UK: "Vistara", "6E": "IndiGo", EK: "Emirates", QR: "Qatar Airways", BA: "British Airways" };
const minutes = (iso) => new Date(iso).getHours() * 60 + new Date(iso).getMinutes();
const durationMinutes = (iso) => { const match = String(iso || "").match(/PT(?:(\d+)H)?(?:(\d+)M)?/); return (Number(match?.[1]) || 0) * 60 + (Number(match?.[2]) || 0); };
const formatSegment = (segment) => ({ airline: carrierNames[segment.carrierCode] || segment.carrierCode, airlineCode: segment.carrierCode, flightNumber: `${segment.carrierCode}${segment.number}`, departure: { airport: segment.departure.iataCode, time: segment.departure.at }, arrival: { airport: segment.arrival.iataCode, time: segment.arrival.at }, duration: segment.duration, aircraft: segment.aircraft?.code || "", terminal: segment.departure.terminal || segment.arrival.terminal || "" });
function normaliseOffer(offer) { const itinerary = offer.itineraries?.[0]; const segments = itinerary?.segments || []; const first = segments[0]; const last = segments.at(-1); return { id: offer.id, airline: carrierNames[first?.carrierCode] || first?.carrierCode || "Airline", airlineCode: first?.carrierCode || "", flightNumber: `${first?.carrierCode || ""}${first?.number || ""}`, departure: { airport: first?.departure?.iataCode || "", time: first?.departure?.at || "" }, arrival: { airport: last?.arrival?.iataCode || "", time: last?.arrival?.at || "" }, duration: itinerary?.duration || "", durationMinutes: durationMinutes(itinerary?.duration), stops: Math.max(0, segments.length - 1), cabin: first?.cabin || "ECONOMY", price: Number(offer.price?.grandTotal || 0), currency: offer.price?.currency || "USD", baggage: offer.travelerPricings?.[0]?.fareDetailsBySegment?.[0]?.includedCheckedBags?.quantity != null ? `${offer.travelerPricings[0].fareDetailsBySegment[0].includedCheckedBags.quantity} checked bag` : "Baggage details unavailable", bookingUrl: "https://www.amadeus.com/en/booking", itinerary: segments.map(formatSegment), fareRules: offer.travelerPricings?.[0]?.fareDetailsBySegment?.[0]?.brandedFare || "Fare rules provided by airline" }; }
async function token(config) { const response = await fetch("https://test.api.amadeus.com/v1/security/oauth2/token", { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ grant_type: "client_credentials", client_id: config.amadeusClientId, client_secret: config.amadeusClientSecret }) }); if (!response.ok) throw new Error("Amadeus authentication failed"); return (await response.json()).access_token; }
async function cityCode(city, accessToken) { const response = await fetch(`https://test.api.amadeus.com/v1/reference-data/locations?subType=CITY&keyword=${encodeURIComponent(city)}&page%5Blimit%5D=1`, { headers: { Authorization: `Bearer ${accessToken}` } }); const data = await response.json(); if (!response.ok || !data?.data?.[0]?.iataCode) throw new Error(`No airport city code found for "${city}".`); return data.data[0].iataCode; }
function mockFlights(search) { const airlines = [["AI", "Air India"], ["6E", "IndiGo"], ["UK", "Vistara"], ["EK", "Emirates"], ["QR", "Qatar Airways"], ["BA", "British Airways"], ["AI", "Air India"], ["6E", "IndiGo"]]; return airlines.map(([code, airline], index) => { const hour = 5 + index * 2; const departureTime = `${search.departureDate}T${String(hour % 24).padStart(2, "0")}:15:00`; const duration = 115 + (index % 3) * 75; const arrivalTime = new Date(new Date(departureTime).getTime() + duration * 60000).toISOString().slice(0, 19); const stops = index % 4 === 0 ? 0 : index % 3; return { id: `mock-flight-${index}`, airline, airlineCode: code, flightNumber: `${code}${120 + index * 37}`, departure: { airport: search.departure.slice(0, 3).toUpperCase(), time: departureTime }, arrival: { airport: search.destination.slice(0, 3).toUpperCase(), time: arrivalTime }, duration: `PT${Math.floor(duration / 60)}H${duration % 60}M`, durationMinutes: duration, stops, cabin: ["ECONOMY", "PREMIUM_ECONOMY", "BUSINESS", "FIRST"][index % 4], price: 7200 + index * 1850, currency: "INR", baggage: index % 2 ? "1 checked bag" : "Cabin bag included", bookingUrl: `https://www.google.com/travel/flights?q=${encodeURIComponent(`${search.departure} to ${search.destination}`)}`, itinerary: [{ airline, airlineCode: code, flightNumber: `${code}${120 + index * 37}`, departure: { airport: search.departure.slice(0, 3).toUpperCase(), time: departureTime }, arrival: { airport: search.destination.slice(0, 3).toUpperCase(), time: arrivalTime }, duration: `PT${Math.floor(duration / 60)}H${duration % 60}M`, aircraft: "A320", terminal: "1" }], fareRules: "Changes and refunds are subject to airline fare conditions." }; }); }
export function createFlightProvider(config) { return { async search(search) { if (!config.amadeusClientId || !config.amadeusClientSecret) return { flights: mockFlights(search), source: "demo" }; const accessToken = await token(config); const [originLocationCode, destinationLocationCode] = await Promise.all([cityCode(search.departure, accessToken), cityCode(search.destination, accessToken)]); const parameters = new URLSearchParams({ originLocationCode, destinationLocationCode, departureDate: search.departureDate, adults: String(search.travelers), max: "20", currencyCode: "INR" }); if (search.returnDate) parameters.set("returnDate", search.returnDate); const response = await fetch(`https://test.api.amadeus.com/v2/shopping/flight-offers?${parameters}`, { headers: { Authorization: `Bearer ${accessToken}` } }); const data = await response.json(); if (!response.ok) throw new Error(data?.errors?.[0]?.detail || "Amadeus flight search failed"); return { flights: (data.data || []).map(normaliseOffer), source: "amadeus" }; } }; }
