import mongoose from "mongoose";
import { Favorite, Flight, Hotel, Restaurant, SearchHistory, Trip } from "../models/TravelData.mjs";

const savedModels = { hotels: Hotel, restaurants: Restaurant, flights: Flight };
const safePage = (value) => Math.max(1, Math.min(Number(value) || 1, 10000));
const safeLimit = (value) => Math.max(1, Math.min(Number(value) || 12, 50));
const validId = (value) => mongoose.isValidObjectId(value);
const notFound = (response, message = "Saved item not found.") => response.status(404).json({ success: false, error: { message } });

export async function listTrips(request, response, next) {
  try { const page = safePage(request.query.page); const limit = safeLimit(request.query.limit); const filter = { userId: request.user.id }; if (request.query.favorite === "true") filter.favorite = true; const [trips, total] = await Promise.all([Trip.find(filter).sort({ createdAt: -1 }).skip((page - 1) * limit).limit(limit).lean(), Trip.countDocuments(filter)]); response.json({ success: true, trips, pagination: { page, limit, total, pages: Math.ceil(total / limit) } }); } catch (error) { next(error); }
}
export async function getTrip(request, response, next) { try { if (!validId(request.params.id)) return notFound(response); const trip = await Trip.findOne({ _id: request.params.id, userId: request.user.id }).lean(); return trip ? response.json({ success: true, trip }) : notFound(response); } catch (error) { next(error); } }
export async function createTrip(request, response, next) { try { const trip = await Trip.create(normalizeTrip(request.body, request.user.id)); response.status(201).json({ success: true, trip }); } catch (error) { next(error); } }
export async function updateTrip(request, response, next) { try { if (!validId(request.params.id)) return notFound(response); const allowed = ["destination", "startDate", "endDate", "budget", "currency", "itinerary", "weatherSnapshot", "selectedHotel", "selectedRestaurant", "selectedFlight", "favorite", "status"]; const update = {}; for (const key of allowed) if (request.body[key] !== undefined) update[key] = request.body[key]; const trip = await Trip.findOneAndUpdate({ _id: request.params.id, userId: request.user.id }, update, { returnDocument: "after", runValidators: true }).lean(); return trip ? response.json({ success: true, trip }) : notFound(response); } catch (error) { next(error); } }
export async function deleteTrip(request, response, next) { try { if (!validId(request.params.id)) return notFound(response); const trip = await Trip.findOneAndDelete({ _id: request.params.id, userId: request.user.id }); if (!trip) return notFound(response); await Favorite.deleteOne({ userId: request.user.id, entityType: "trip", entityId: String(trip._id) }); response.json({ success: true }); } catch (error) { next(error); } }
export async function duplicateTrip(request, response, next) { try { if (!validId(request.params.id)) return notFound(response); const source = await Trip.findOne({ _id: request.params.id, userId: request.user.id }).lean(); if (!source) return notFound(response); delete source._id; delete source.createdAt; delete source.updatedAt; source.destination = `${source.destination} (Copy)`; source.favorite = false; const trip = await Trip.create(source); response.status(201).json({ success: true, trip }); } catch (error) { next(error); } }
export async function toggleTripFavorite(request, response, next) { try { if (!validId(request.params.id)) return notFound(response); const trip = await Trip.findOne({ _id: request.params.id, userId: request.user.id }); if (!trip) return notFound(response); trip.favorite = request.body.favorite === undefined ? !trip.favorite : Boolean(request.body.favorite); await trip.save(); const key = { userId: request.user.id, entityType: "trip", entityId: String(trip._id) }; if (trip.favorite) await Favorite.findOneAndUpdate(key, { ...key, data: { destination: trip.destination, startDate: trip.startDate } }, { upsert: true }); else await Favorite.deleteOne(key); response.json({ success: true, trip }); } catch (error) { next(error); } }

export async function listSaved(request, response, next) { try { const Model = savedModels[request.params.type]; if (!Model) return response.status(400).json({ success: false, error: { message: "Invalid saved item type." } }); const page = safePage(request.query.page); const limit = safeLimit(request.query.limit); const filter = { userId: request.user.id }; const [items, total] = await Promise.all([Model.find(filter).sort({ createdAt: -1 }).skip((page - 1) * limit).limit(limit).lean(), Model.countDocuments(filter)]); response.json({ success: true, items, pagination: { page, limit, total, pages: Math.ceil(total / limit) } }); } catch (error) { next(error); } }
export async function saveProviderItem(request, response, next) { try { const Model = savedModels[request.params.type]; const data = request.body.data; const providerId = String(request.body.providerId || data?.id || ""); if (!Model || !providerId || !data || typeof data !== "object") return response.status(400).json({ success: false, error: { message: "Enter valid saved item details." } }); const key = { userId: request.user.id, providerId }; const item = await Model.findOneAndUpdate(key, { ...key, data }, { upsert: true, returnDocument: "after", runValidators: true }); await Favorite.findOneAndUpdate({ userId: request.user.id, entityType: request.params.type.slice(0, -1), entityId: providerId }, { userId: request.user.id, entityType: request.params.type.slice(0, -1), entityId: providerId, data }, { upsert: true }); response.status(201).json({ success: true, item }); } catch (error) { next(error); } }
export async function deleteSaved(request, response, next) { try { const Model = savedModels[request.params.type]; if (!Model) return response.status(400).json({ success: false, error: { message: "Invalid saved item type." } }); await Promise.all([Model.deleteOne({ userId: request.user.id, providerId: request.params.providerId }), Favorite.deleteOne({ userId: request.user.id, entityType: request.params.type.slice(0, -1), entityId: request.params.providerId })]); response.json({ success: true }); } catch (error) { next(error); } }
export async function recordSearch(request, response, next) { try { const query = String(request.body.query || "").trim(); if (!query) return response.status(400).json({ success: false, error: { message: "Search query is required." } }); const item = await SearchHistory.create({ userId: request.user.id, query, category: request.body.category, metadata: request.body.metadata }); response.status(201).json({ success: true, item }); } catch (error) { next(error); } }
export async function deleteSearch(request, response, next) { try { if (!validId(request.params.id)) return notFound(response, "Recent search not found."); const item = await SearchHistory.findOneAndDelete({ _id: request.params.id, userId: request.user.id }); return item ? response.json({ success: true, message: "Recent search removed successfully" }) : notFound(response, "Recent search not found."); } catch (error) { next(error); } }
export async function dashboard(request, response, next) { try { const now = new Date(); const userId = request.user._id; const [upcomingTrips, pastTrips, favoriteDestinations, savedHotels, savedRestaurants, savedFlights, recentSearches, tripCount, favoriteTrips] = await Promise.all([Trip.find({ userId, startDate: { $gte: now } }).sort({ startDate: 1 }).limit(5).lean(), Trip.find({ userId, endDate: { $lt: now } }).sort({ endDate: -1 }).limit(5).lean(), Favorite.find({ userId, entityType: "destination" }).sort({ createdAt: -1 }).limit(8).lean(), Hotel.find({ userId }).sort({ createdAt: -1 }).limit(8).lean(), Restaurant.find({ userId }).sort({ createdAt: -1 }).limit(8).lean(), Flight.find({ userId }).sort({ createdAt: -1 }).limit(8).lean(), SearchHistory.find({ userId }).sort({ createdAt: -1 }).limit(10).lean(), Trip.countDocuments({ userId }), Trip.countDocuments({ userId, favorite: true })]); response.json({ success: true, dashboard: { upcomingTrips, pastTrips, favoriteDestinations, savedHotels, savedRestaurants, savedFlights, recentSearches, statistics: { totalTrips: tripCount, favoriteTrips, countriesVisited: new Set(pastTrips.map((trip) => trip.destination)).size } } }); } catch (error) { next(error); } }

function normalizeTrip(body, userId) { return { userId, destination: String(body.destination || "Untitled destination").trim(), startDate: body.startDate || undefined, endDate: body.endDate || undefined, budget: Number(body.budget) || 0, currency: body.currency || "INR", itinerary: String(body.itinerary || "").trim(), weatherSnapshot: body.weatherSnapshot, selectedHotel: body.selectedHotel, selectedRestaurant: body.selectedRestaurant, selectedFlight: body.selectedFlight, favorite: Boolean(body.favorite), status: body.status || "planned" }; }
