import { useState } from "react";
import { Link, Navigate, useLocation, useNavigate, useParams } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import Toast from "../components/Toast";
import "./auth.css";

const strength = "Use 8+ characters with uppercase, lowercase, a number, and a symbol.";
function AuthLayout({ eyebrow, title, copy, children }) { return <main className="auth-page"><Link className="auth-brand" to="/"><span>✦</span> Roamly</Link><section className="auth-panel"><div className="auth-art"><p>{eyebrow}</p><h1>{title}</h1><span>{copy}</span><div className="auth-orb one" /><div className="auth-orb two" /></div><div className="auth-card"><Link className="auth-home-button" to="/">← Back to home</Link>{children}</div></section></main>; }
function PasswordField({ label, ...props }) { const [visible, setVisible] = useState(false); return <label className="auth-field"><span>{label}</span><div><input {...props} type={visible ? "text" : "password"} /><button type="button" onClick={() => setVisible((v) => !v)} aria-label={`${visible ? "Hide" : "Show"} password`}>{visible ? "Hide" : "Show"}</button></div></label>; }
function Submit({ loading, children }) { return <button className="auth-submit" disabled={loading}>{loading ? <><i className="auth-spinner" />Please wait…</> : children}</button>; }

export function LoginPage() {
  const { user, login, sessionMessage, clearSessionMessage } = useAuth(); const navigate = useNavigate(); const location = useLocation();
  const [form, setForm] = useState({ email: "", password: "", rememberMe: false }); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  if (user) return <Navigate to={location.state?.from?.pathname || "/profile"} replace />;
  const submit = async (event) => { event.preventDefault(); setBusy(true); setError(""); try { await login(form); navigate(location.state?.from?.pathname || "/profile", { replace: true }); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  return <AuthLayout eyebrow="WELCOME BACK" title="Your next journey is waiting." copy="Sign in to revisit saved escapes and continue planning."><Toast message={error || sessionMessage} type="error" onClose={() => { setError(""); clearSessionMessage(); }} /><h2>Log in</h2><p>New to Roamly? <Link to="/signup">Create an account</Link></p><form onSubmit={submit}><label className="auth-field"><span>Email address</span><input type="email" autoComplete="email" required value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label><PasswordField label="Password" autoComplete="current-password" required value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /><div className="auth-row"><label><input type="checkbox" checked={form.rememberMe} onChange={(e) => setForm({ ...form, rememberMe: e.target.checked })} /> Remember me</label><Link to="/forgot-password">Forgot password?</Link></div><Submit loading={busy}>Log in <span>→</span></Submit></form></AuthLayout>;
}

export function SignupPage() {
  const { user, register } = useAuth(); const navigate = useNavigate(); const [form, setForm] = useState({ fullName: "", email: "", password: "", confirmPassword: "", rememberMe: true }); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  if (user) return <Navigate to="/profile" replace />;
  const submit = async (e) => { e.preventDefault(); setBusy(true); setError(""); try { await register(form); navigate("/profile"); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  return <AuthLayout eyebrow="JOIN ROAMLY" title="Collect moments, not tabs." copy="Keep every destination, stay, and itinerary together."><Toast message={error} type="error" onClose={() => setError("")} /><h2>Create account</h2><p>Already a traveler here? <Link to="/login">Log in</Link></p><form onSubmit={submit}><label className="auth-field"><span>Full name</span><input autoComplete="name" required minLength="2" value={form.fullName} onChange={(e) => setForm({ ...form, fullName: e.target.value })} /></label><label className="auth-field"><span>Email address</span><input type="email" autoComplete="email" required value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label><PasswordField label="Password" autoComplete="new-password" required pattern="(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^A-Za-z\d]).{8,72}" title={strength} value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /><small className="auth-hint">{strength}</small><PasswordField label="Confirm password" autoComplete="new-password" required value={form.confirmPassword} onChange={(e) => setForm({ ...form, confirmPassword: e.target.value })} /><Submit loading={busy}>Create account <span>→</span></Submit></form></AuthLayout>;
}

export function ForgotPasswordPage() { const { request } = useAuth(); const [email, setEmail] = useState(""); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(""); const submit = async (e) => { e.preventDefault(); setBusy(true); try { const data = await request("/forgot-password", { method: "POST", body: JSON.stringify({ email }) }); setNotice(data.resetUrl ? `${data.message} Development link: ${data.resetUrl}` : data.message); } catch (err) { setNotice(err.message); } finally { setBusy(false); } }; return <AuthLayout eyebrow="RESET ACCESS" title="A small detour." copy="We’ll help you get back to your travel plans."><Toast message={notice} onClose={() => setNotice("")} /><h2>Forgot password?</h2><p>Enter your account email to receive a secure reset link.</p><form onSubmit={submit}><label className="auth-field"><span>Email address</span><input type="email" required value={email} onChange={(e) => setEmail(e.target.value)} /></label><Submit loading={busy}>Send reset link</Submit><Link className="auth-back" to="/login">← Back to login</Link></form></AuthLayout>; }

export function ResetPasswordPage() { const { request } = useAuth(); const { token } = useParams(); const navigate = useNavigate(); const [form, setForm] = useState({ password: "", confirmPassword: "" }); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const submit = async (e) => { e.preventDefault(); setBusy(true); try { await request("/reset-password", { method: "POST", body: JSON.stringify({ token, ...form }) }); navigate("/login", { state: { reset: true } }); } catch (err) { setError(err.message); } finally { setBusy(false); } }; return <AuthLayout eyebrow="NEW PASSWORD" title="Back on course." copy="Choose a strong password you haven’t used before."><Toast message={error} type="error" onClose={() => setError("")} /><h2>Reset password</h2><form onSubmit={submit}><PasswordField label="New password" required value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /><small className="auth-hint">{strength}</small><PasswordField label="Confirm password" required value={form.confirmPassword} onChange={(e) => setForm({ ...form, confirmPassword: e.target.value })} /><Submit loading={busy}>Save new password</Submit></form></AuthLayout>; }
