import { useState } from "react";
import { Link } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import Toast from "../components/Toast";
import "./auth.css";

const initials = (name = "Traveler") => name.split(/\s+/).map((part) => part[0]).slice(0, 2).join("").toUpperCase();
function AccountNav() { const { user, logout } = useAuth(); return <header className="account-nav"><Link className="auth-brand" to="/"><span>✦</span> Roamly</Link><nav><Link to="/profile">Profile</Link><Link to="/saved-trips">Saved trips</Link><Link to="/favorites">Favorites</Link><Link to="/settings">Settings</Link><button onClick={logout}>Log out</button></nav><span className="account-avatar">{user.profilePicture ? <img src={user.profilePicture} alt="" /> : initials(user.fullName)}</span></header>; }
export function ProfilePage() { const { user } = useAuth(); const cards = [["Saved trips", user.savedTrips?.length || 0], ["Favorite destinations", user.favoriteDestinations?.length || 0], ["Saved hotels", user.savedHotels?.length || 0], ["Saved restaurants", user.savedRestaurants?.length || 0]]; return <main className="account-page"><AccountNav /><section className="account-hero"><div className="profile-avatar">{user.profilePicture ? <img src={user.profilePicture} alt="Profile" /> : initials(user.fullName)}</div><div><p>TRAVELER PROFILE</p><h1>{user.fullName}</h1><span>{user.email}</span></div><Link className="account-primary" to="/settings">Edit profile</Link></section><section className="account-grid">{cards.map(([label, value]) => <article key={label}><strong>{value}</strong><span>{label}</span></article>)}</section><section className="preference-card"><h2>Your travel preferences</h2><div><p><span>Preferred currency</span><strong>{user.preferredCurrency || "USD"}</strong></p><p><span>Preferred language</span><strong>{user.preferredLanguage || "English"}</strong></p><p><span>Country</span><strong>{user.country || "Not set"}</strong></p></div></section></main>; }
export function SettingsPage() { const { user, updateProfile, request } = useAuth(); const [profile, setProfile] = useState({ fullName: user.fullName || "", profilePicture: user.profilePicture || "", phoneNumber: user.phoneNumber || "", country: user.country || "", preferredCurrency: user.preferredCurrency || "USD", preferredLanguage: user.preferredLanguage || "English" }); const [password, setPassword] = useState({ currentPassword: "", newPassword: "", confirmPassword: "" }); const [busy, setBusy] = useState(false); const [toast, setToast] = useState({ message: "", type: "success" }); const saveProfile = async (e) => { e.preventDefault(); setBusy(true); try { await updateProfile(profile); setToast({ message: "Profile updated successfully.", type: "success" }); } catch (err) { setToast({ message: err.message, type: "error" }); } finally { setBusy(false); } }; const savePassword = async (e) => { e.preventDefault(); setBusy(true); try { const data = await request("/change-password", { method: "PUT", body: JSON.stringify(password) }); setToast({ message: data.message, type: "success" }); setPassword({ currentPassword: "", newPassword: "", confirmPassword: "" }); } catch (err) { setToast({ message: err.message, type: "error" }); } finally { setBusy(false); } }; return <main className="account-page"><AccountNav /><Toast {...toast} onClose={() => setToast({ message: "" })} /><header className="settings-title"><p>ACCOUNT SETTINGS</p><h1>Make Roamly yours.</h1></header><div className="settings-grid"><form className="settings-card" onSubmit={saveProfile}><h2>Profile & preferences</h2>{Object.entries(profile).map(([key, value]) => <label key={key}><span>{key.replace(/([A-Z])/g, " $1").replace(/^./, (c) => c.toUpperCase())}</span>{key === "preferredCurrency" ? <select value={value} onChange={(e) => setProfile({ ...profile, [key]: e.target.value })}>{["USD", "EUR", "GBP", "INR", "JPY", "AUD", "CAD"].map((x) => <option key={x}>{x}</option>)}</select> : <input required={key === "fullName"} value={value} onChange={(e) => setProfile({ ...profile, [key]: e.target.value })} />}</label>)}<button disabled={busy}>Save changes</button></form><form className="settings-card" onSubmit={savePassword}><h2>Change password</h2>{[["currentPassword", "Current password"], ["newPassword", "New password"], ["confirmPassword", "Confirm new password"]].map(([key, label]) => <label key={key}><span>{label}</span><input type="password" required value={password[key]} onChange={(e) => setPassword({ ...password, [key]: e.target.value })} /></label>)}<button disabled={busy}>Update password</button></form></div></main>; }
export function SavedTripsPage({ favorites = false }) { const { user } = useAuth(); const items = favorites ? user.favoriteDestinations : user.savedTrips; return <main className="account-page"><AccountNav /><header className="settings-title"><p>YOUR COLLECTION</p><h1>{favorites ? "Favorite destinations" : "Saved trips"}</h1></header><section className="empty-library"><span>{favorites ? "♡" : "◇"}</span><h2>{items?.length ? `${items.length} saved item${items.length === 1 ? "" : "s"}` : "Nothing saved yet"}</h2><p>Explore Roamly and save the places and plans that inspire you.</p><Link className="account-primary" to="/">Start exploring</Link></section></main>; }
