import { useCallback, useEffect, useState } from "react";
import { jsPDF } from "jspdf";
import { Link } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import { deleteTrip, duplicateTrip, favoriteTrip, getDashboard, listTrips, updateTrip } from "../services/travelDataService";
import Toast from "../components/Toast";
import "./travelDashboard.css";

const date = (value) => value ? new Date(value).toLocaleDateString(undefined, { day: "numeric", month: "short", year: "numeric" }) : "Flexible";
const initials = (name = "Traveler") => name.split(/\s+/).map((part) => part[0]).slice(0, 2).join("").toUpperCase();
function DashboardNav() { const { user, logout } = useAuth(); return <header className="account-nav"><Link className="auth-brand" to="/"><span>✦</span> Roamly</Link><nav><Link to="/profile">Dashboard</Link><Link to="/saved-trips">Trips</Link><Link to="/favorites">Favorites</Link><Link to="/settings">Settings</Link><button onClick={logout}>Log out</button></nav><span className="account-avatar">{user.profilePicture ? <img src={user.profilePicture} alt="" /> : initials(user.fullName)}</span></header>; }
function LoadingCards() { return <div className="dashboard-cards">{[1,2,3,4].map((x) => <div className="dashboard-skeleton" key={x} />)}</div>; }

export function DashboardPage() {
  const { user } = useAuth(); const [state, setState] = useState({ loading: true, data: null, error: "" });
  const load = useCallback(() => { setState((s) => ({ ...s, loading: true, error: "" })); getDashboard().then((result) => setState({ loading: false, data: result.dashboard, error: "" })).catch((error) => setState({ loading: false, data: null, error: error.message })); }, []);
  useEffect(load, [load]); const data = state.data;
  return <main className="account-page"><DashboardNav /><section className="dashboard-heading"><div><p>WELCOME BACK</p><h1>{user.fullName}, where next?</h1><span>Your plans, saved places, and recent travel activity in one view.</span></div><Link to="/" className="account-primary">Plan a new trip</Link></section>{state.loading ? <LoadingCards /> : state.error ? <div className="dashboard-error"><p>{state.error}</p><button onClick={load}>Retry</button></div> : <><section className="dashboard-stats">{[["Total trips",data.statistics.totalTrips],["Favorite trips",data.statistics.favoriteTrips],["Upcoming",data.upcomingTrips.length],["Saved places",data.savedHotels.length+data.savedRestaurants.length+data.savedFlights.length]].map(([label,value]) => <article key={label}><strong>{value}</strong><span>{label}</span></article>)}</section><DashboardSection title="Upcoming trips" items={data.upcomingTrips} type="trip" empty="No upcoming trips yet." /><div className="dashboard-columns"><DashboardSection title="Saved hotels" items={data.savedHotels} /><DashboardSection title="Saved restaurants" items={data.savedRestaurants} /><DashboardSection title="Saved flights" items={data.savedFlights} /></div><DashboardSection title="Recent searches" items={data.recentSearches} type="search" empty="Search activity will appear here." /></>}</main>;
}
function DashboardSection({ title, items = [], type, empty = "Nothing saved yet." }) { return <section className="dashboard-section"><h2>{title}</h2>{items.length ? <div className="dashboard-list">{items.map((item) => { const value = item.data || item; return <article key={item._id}><strong>{type === "search" ? item.query : value.destination || value.name || value.airline || value.flightNumber || "Saved item"}</strong><span>{type === "trip" ? `${date(value.startDate)} – ${date(value.endDate)}` : type === "search" ? item.category : value.address || value.flightNumber || date(item.createdAt)}</span></article>; })}</div> : <p className="dashboard-empty">{empty}</p>}</section>; }

export function MongoTripsPage({ favoritesOnly = false }) {
  const [state, setState] = useState({ loading: true, trips: [], page: 1, pages: 1 }); const [toast, setToast] = useState({ message: "", type: "success" }); const [editing, setEditing] = useState(null);
  const load = useCallback(async (page = 1) => { setState((s) => ({ ...s, loading: true })); try { const result = await listTrips(page); const trips = favoritesOnly ? result.trips.filter((trip) => trip.favorite) : result.trips; setState({ loading: false, trips, page: result.pagination.page, pages: result.pagination.pages }); } catch (error) { setState((s) => ({ ...s, loading: false })); setToast({ message: error.message, type: "error" }); } }, [favoritesOnly]); useEffect(() => { load(); }, [load]);
  const action = async (work, success) => { try { await work(); setToast({ message: success, type: "success" }); await load(state.page); } catch (error) { setToast({ message: error.message, type: "error" }); } };
  const download = (trip) => { const pdf = new jsPDF(); pdf.setFontSize(18); pdf.text(trip.destination, 16, 18); pdf.setFontSize(10); const lines = pdf.splitTextToSize(trip.itinerary, 178); let y=30; lines.forEach((line) => { if(y>282){pdf.addPage();y=18;} pdf.text(line,16,y);y+=5; }); pdf.save(`${trip.destination.replace(/[^a-z0-9]+/gi,"-").toLowerCase()}-itinerary.pdf`); };
  return <main className="account-page"><DashboardNav /><Toast {...toast} onClose={() => setToast({ message: "" })} /><header className="dashboard-heading"><div><p>YOUR TRAVEL LIBRARY</p><h1>{favoritesOnly ? "Favorite trips" : "Saved trips"}</h1><span>Every AI itinerary is saved automatically.</span></div><Link to="/" className="account-primary">Create trip</Link></header>{state.loading ? <LoadingCards /> : state.trips.length ? <section className="trip-library">{state.trips.map((trip) => <article className="mongo-trip" key={trip._id}><div><span>{trip.favorite ? "★ Favorite" : "Saved trip"}</span><h2>{trip.destination}</h2><p>{date(trip.startDate)} – {date(trip.endDate)} · {trip.currency} {trip.budget?.toLocaleString()}</p></div><p>{trip.itinerary.slice(0,180)}…</p><div className="trip-actions"><button onClick={() => action(() => favoriteTrip(trip._id,!trip.favorite),trip.favorite?"Removed from favorites.":"Marked as favorite.")}>{trip.favorite ? "Unfavorite" : "Favorite"}</button><button onClick={() => setEditing(trip)}>Edit</button><button onClick={() => action(() => duplicateTrip(trip._id),"Trip duplicated.")}>Duplicate</button><button onClick={() => download(trip)}>PDF</button><button className="danger" onClick={() => window.confirm("Delete this trip permanently?") && action(() => deleteTrip(trip._id),"Trip deleted.")}>Delete</button></div></article>)}</section> : <div className="empty-library"><span>◇</span><h2>No saved trips yet</h2><p>Create an AI itinerary and it will appear here automatically.</p></div>}{state.pages>1&&<div className="pagination"><button disabled={state.page<=1} onClick={() => load(state.page-1)}>Previous</button><span>{state.page} / {state.pages}</span><button disabled={state.page>=state.pages} onClick={() => load(state.page+1)}>Next</button></div>}{editing&&<EditTrip trip={editing} onClose={() => setEditing(null)} onSave={(values) => action(() => updateTrip(editing._id,values),"Trip updated.").then(() => setEditing(null))} />}</main>;
}
function EditTrip({ trip, onClose, onSave }) { const [values,setValues]=useState({destination:trip.destination,startDate:trip.startDate?.slice(0,10)||"",endDate:trip.endDate?.slice(0,10)||"",budget:trip.budget,currency:trip.currency,itinerary:trip.itinerary}); return <div className="edit-backdrop" onMouseDown={onClose}><form className="edit-trip" onSubmit={(e)=>{e.preventDefault();onSave(values);}} onMouseDown={(e)=>e.stopPropagation()}><button type="button" className="edit-close" onClick={onClose}>×</button><h2>Edit trip</h2><label>Destination<input value={values.destination} onChange={(e)=>setValues({...values,destination:e.target.value})} required /></label><div className="edit-dates"><label>Start date<input type="date" value={values.startDate} onChange={(e)=>setValues({...values,startDate:e.target.value})} /></label><label>End date<input type="date" value={values.endDate} onChange={(e)=>setValues({...values,endDate:e.target.value})} /></label></div><label>Budget<input type="number" min="0" value={values.budget} onChange={(e)=>setValues({...values,budget:e.target.value})} /></label><label>Itinerary<textarea rows="12" value={values.itinerary} onChange={(e)=>setValues({...values,itinerary:e.target.value})} required /></label><button className="account-primary">Save changes</button></form></div>; }
